markdown: rdiscount 解析器类型
# markdown: kramdown
# 开启代码高亮
pygments: true
auto: true

title : Doin
tagline: Site Tagline

author :
  name : Doin
  email : doin@foxmail.com
  github : doin
  twitter : doin
  feedburner : feedname

JB :
  version : 0.2.0

  BASE_PATH : false

  ASSET_PATH : false

  #archive_path: /archive.html
  #categories_path : /categories.html
  tags_path : /tags.html
  #about_path : /about.html 
  comments :
    provider : disqus
    disqus :
      short_name : doin
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light